[package]
name = "socketbridge"
version = "0.1.0"
edition = "2021"

description = "A bridge application for AF_UNIX and TCP sockets."
authors = ["Michael Schulte"]
license = "MIT"
repository = "https://github.com/michael72/socketbridge"

[dependencies]
